### ISSUE TITLE
rails s や rails db:createで落ちる（docker on mac）

### ISSUE THREAD

**Issue by momocus** [momocus/sakazuki#475]
### environment

Docker Desktop 4.7.0 (77141) 

### Describe the bug

```
$ docker-compose run --rm web bundle exec rails c
Creating sakazuki_web_run ... done
/usr/local/bundle/gems/listen-3.7.1/lib/listen/event/loop.rb:57:in `start': thread didn't start in 5.0 seconds (in state: :starting) (Listen::Error::NotStarted)
        from /usr/local/bundle/gems/listen-3.7.1/lib/listen/listener.rb:75:in `block in <class:Listener>'
        from /usr/local/bundle/gems/listen-3.7.1/lib/listen/fsm.rb:124:in `instance_eval'
        from /usr/local/bundle/gems/listen-3.7.1/lib/listen/fsm.rb:124:in `call'
        from /usr/local/bundle/gems/listen-3.7.1/lib/listen/fsm.rb:105:in `transition_with_callbacks!'
        from /usr/local/bundle/gems/listen-3.7.1/lib/listen/fsm.rb:72:in `transition'
        from /usr/local/bundle/gems/listen-3.7.1/lib/listen/listener.rb:93:in `start'
        from /usr/local/bundle/gems/activesupport-7.0.2.2/lib/active_support/evented_file_update_checker.rb:109:in `start'
        from /usr/local/bundle/gems/activesupport-7.0.2.2/lib/active_support/evented_file_update_checker.rb:89:in `block in initialize'
        from /usr/local/bundle/gems/activesupport-7.0.2.2/lib/active_support/fork_tracker.rb:43:in `each'
        from /usr/local/bundle/gems/activesupport-7.0.2.2/lib/active_support/fork_tracker.rb:43:in `check!'
        from /usr/local/bundle/gems/activesupport-7.0.2.2/lib/active_support/fork_tracker.rb:9:in `_fork'
        from /usr/local/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/session.rb:2121:in `fork'
        from /usr/local/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/session.rb:2121:in `fork'
        from /usr/local/bundle/gems/spring-4.0.0/lib/spring/application.rb:181:in `serve'
        from /usr/local/bundle/gems/spring-4.0.0/lib/spring/application.rb:144:in `block in run'
        from /usr/local/bundle/gems/spring-4.0.0/lib/spring/application.rb:138:in `loop'
        from /usr/local/bundle/gems/spring-4.0.0/lib/spring/application.rb:138:in `run'
        from /usr/local/bundle/gems/spring-4.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from -e:1:in `<main>'
                     
```

**Comment by momocus** [comment]
ぐぐってみたらdebug gemの問題っぽい。
debugのバージョンを1.4.0->1.5.0に上げたら解消した。
