### ISSUE TITLE
:bug:SimpleLightboxが壊れている

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#572]
いつの間にか壊れていた

## 再現手順

- 画像がある酒showを開く
- 画像をクリック
- 画像ページが開いてしまう

## 期待される動作

- 画像がある酒showを開く
- 画像をクリック
- 画像showの上にSimpleLightboxで画像がオーバーレイ表示される

**Comment by yonta** [comment]
#439 を先にやれば、直す必要はない

**Comment by yonta** [comment]
SimpleLightboxのデフォルト`fileExt`（どの拡張子で動かすかのチェック）が`'png|jpg|jpeg|gif'`となっているので、avifが入っていなかったせい。
`false`にするか、拡張子を正規表現で指定する。

- https://simplelightbox.com/

**Comment by yonta** [comment]
SimpleLightboxをどのCSSクラスに適用するかで`img`の`a`タグ指定をしているので、こっちは拡張子指定しなくていいかなと思う。

**Comment by yonta** [comment]
はい、詫びテスト入れたらテスト通らなくなりました。
GitHub Actions上でだけの減少

```console
DEBUGGER: Attaching after process 2310 fork to child process 2471
.........................................................................................................................................................................................................................F.............................................

Failures:

  1) Sake Show Simple Lightboxes with avif photo has same path
     Failure/Error: FactoryBot.create_list(:photo, photo_count, sake:, image:)

     ActiveRecord::RecordInvalid:
       バリデーションに失敗しました: ImageMiniMagickがファイルを処理できませんでした。画像を確認してください。エラーメッセージ: `convert /home/runner/work/sakazuki/sakazuki/tmp/1677651537-745478452060114-0004-0984/thumb/sake_photo1.avif -auto-orient /tmp/image_processing20230301-2310-ezddt2.webp` failed with error:
       convert-im6.q16: no decode delegate for this image format `AVIF' @ error/constitute.c/ReadImage/560.
       convert-im6.q16: no images defined `/tmp/image_processing20230301-2310-ezddt2.webp' @ error/convert.c/ConvertImageCommand/3258.

     [Screenshot Image]: /home/runner/work/sakazuki/sakazuki/tmp/capybara/failures_r_spec_example_groups_sake_show_simple_lightboxes_with_avif_photo_has_same_path_507.png


     # <internal:kernel>:90:in `tap'
     # ./spec/support/factory_bot.rb:8:in `block in sake_with_photos'
     # <internal:kernel>:90:in `tap'
     # ./spec/support/factory_bot.rb:6:in `sake_with_photos'
     # ./spec/system/sake_show_simple_lightboxes_spec.rb:9:in `block (3 levels) in <top (required)>'
     # ./spec/system/sake_show_simple_lightboxes_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 1 minute 7.51 seconds (files took 14.14 seconds to load)
263 examples, 1 failure

Failed examples:

rspec ./spec/system/sake_show_simple_lightboxes_spec.rb:15 # Sake Show Simple Lightboxes with avif photo has same path

Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
Coverage report generated for RSpec to /home/runner/work/sakazuki/sakazuki/coverage/coverage.xml. 288 / 303 LOC (95.05%) covered
Error: Process completed with exit code 1.
```

**Comment by yonta** [comment]
GitHub ActionsのUbuntu latestがfocal。
そのためImageMagickがavifに対応していない。

```console
Run convert -version
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org/
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib
```

さらに、このバージョンのUbuntuにはlibavifがなく対応できない。

```console

Run sudo apt-get install --yes libavif-dev
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libavif-dev
Error: Process completed with exit code 100.
```

**Comment by yonta** [comment]
あとCarrierWaveがエラーすると何も情報ないエラー出す。
エラー内容は「translation missing: ja.errors.messages.mini_magick_processing_error」、翻訳がない。
なのでcarrierwave-i18n gemを入れておくと今後のためにもログが便利そう。

- 参考
  - https://toru-takagi.dev/article/28

**Comment by yonta** [comment]
あれこれ小手先対応するのはよくない。
とりあえず該当テストはコメントアウトしておこう。
別Issueとして、GitHub Actionsのベースイメージが更新されたら直す、っての立てておこう。

**Comment by yonta** [comment]
違うわ。
Firefoxの都合でうbuntu-latestじゃなくてubuntu-20.04使ってたのか。
Firefoxの都合解消してるから、ubuntu-latest使えばいいじゃん。
