### ISSUE TITLE
🖼酒一覧ページの酒画像拡大表示で画像移動ができない

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#683]
## 📝 再現方法

1. 酒一覧ページへいく
2. 画像をクリックする

## 🥰 理想

酒詳細ページでは正しく動いている

- 左右ボタンが正しく動く
- 画像の後ろにページが透過で表示される

![image](https://github.com/momocus/sakazuki/assets/849256/3f0a1275-3f18-4af8-a99a-8293981b1734)

## 🤬 現実

- 左右ボタンが効かない
- 背景が透過しない
- ESCボタンで画像表示を終了できる

![image](https://github.com/momocus/sakazuki/assets/849256/8814edc1-febf-48a1-ab02-da9cd2171487)

## 🌏 環境

fly.io

**Comment by yonta** [comment]
複数画像がまとまっている1要素に対するLightboxとして、酒詳細ページではSimpleLightboxを使っている。

一方で、酒一覧ページでは画像要素がまとまっておらず、複数カード要素に散らばっている。
そこにあまり考えずにSimpleLightboxをテキトウに適用したのが原因な気がする。

**Comment by yonta** [comment]
いやそうでもないな。
指定方法を変えてもうまくいかない。
Turboとの兼ね合いも難しそう。
原因がまだわかっていない。

**Comment by yonta** [comment]
正しく動くshowページ。
`sl-wrapper`クラスのdiv要素内に画像やカウンターやボタンが配置されている。

![image](https://github.com/momocus/sakazuki/assets/849256/7fbc8283-1f9a-40a9-84ea-0c1603bb5352)

**Comment by yonta** [comment]
正しく動かない酒indexの動作ソース。
`sl-wrapper`が大量に展開されている。
`sl-image`内を覗くとどれも同じ画像が入っている。
SimpleLightboxが複数重複展開されているように見える。

![image](https://github.com/momocus/sakazuki/assets/849256/b9a2627f-c3ed-4158-82f2-d59a10c1b632)

**Comment by yonta** [comment]
わかったー！
Stimulus呼び出しをするdata-controllerが各酒カードに適用されているから、SimpleLightboxが複数回呼ばれているんだ。

**Comment by yonta** [comment]
テスト書くか

**Comment by yonta** [comment]
ページ内の`sl-wrapper`が1つしかないってテスト書いておこう。
正しくは2個以上を許さないだけど、まぁ今はわかりやすく1個だけある、でいいか。

**Comment by yonta** [comment]
既存のSimpleLightboxのテストがわかりにくいし、コメントやAAAも変だ。
まずリファクタリングもしておこ。

**Comment by yonta** [comment]
画像を持った酒を、FactoryBotで複数つくると、DBのUniqueキーエラーになる。なんじゃそりゃ。

```console
)$ rspec ./spec/system/simple_lightboxes_spec.rb:59
Run options: include {:locations=>{"./spec/system/simple_lightboxes_spec.rb"=>[59]}}
F

Failures:

  1) Simple Lightboxes with sake index page with multiple sakes exists only one
     Failure/Error: FactoryBot.create(:photo, sake:, image:)

     ActiveRecord::RecordNotUnique:
       PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "photos_pkey"
       DETAIL:  Key (id)=(1) already exists.
     # ./spec/system/simple_lightboxes_spec.rb:44:in `block (4 levels) in <top (required)>'
     # ./spec/system/simple_lightboxes_spec.rb:42:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # PG::UniqueViolation:
     #   ERROR:  duplicate key value violates unique constraint "photos_pkey"
     #   DETAIL:  Key (id)=(1) already exists.
     #   ./spec/system/simple_lightboxes_spec.rb:44:in `block (4 levels) in <top (required)>'

Finished in 4.8 seconds (files took 3.46 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/system/simple_lightboxes_spec.rb:59 # Simple Lightboxes with sake index page with multiple sakes exists only one
```

**Comment by yonta** [comment]
なーんだ。
FactoryBotのPhotoでid固定で指定してただけだった。
肝心なことかできとらんやんけー！！！

```ruby
FactoryBot.define do
  factory :photo do
    id { 1 }
    image { "temp_path" }
    sake
  end
end
```
