### ISSUE TITLE
ESLint v9系へのアップグレード

### ISSUE THREAD

**Issue by yonta** [momocus/sakazuki#816]
大変そう。
Flat Configが導入されたので、コンフィグ込みで移行する。

**Comment by yonta** [comment]
ESLint9からNode v18未満がサポートされなくなった。

ところでNode v18は今年2025年4月まで。
先にNode22に上げたほうがよさそう。

**Comment by yonta** [comment]
このリンク先を見てやっていくぞー！！！！！！！！！うおお！！！！！！！！！

- https://eslint.org/docs/latest/use/migrate-to-9.0.0

**Comment by yonta** [comment]
とりあえず`yarn upgrade-interactive`でESLint v9にする。

**Comment by yonta** [comment]
試しに実行するとコンフィグがないと怒られる。
ESLintバージョンアップ、ヨシ！

```console
$ yarn run eslint

Oops! Something went wrong! :(

ESLint: 9.22.0

ESLint couldn't find an eslint.config.(js|mjs|cjs) file.

From ESLint v9.0.0, the default configuration file is now eslint.config.js.
If you are using a .eslintrc.* file, please follow the migration guide
to update your configuration file to the new format:

https://eslint.org/docs/latest/use/configure/migration-guide

If you still have problems after following the migration guide, please stop by
https://eslint.org/chat/help to chat with the team.

```

**Comment by yonta** [comment]
以降スクリプトもあるらしい。
まずは`yarn create @eslint/config`で初期化された設定が作れるらしいから試そう。

ブラウザ使うか、TS使うか、React使うかとか聞かれて、答えたら以下のようなのが作られた。
package.jsonの依存関係もやや変更された。
```
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";


/** @type {import('eslint').Linter.Config[]} */
export default [
  {files: ["**/*.{js,mjs,cjs,ts}"]},
  {languageOptions: { globals: globals.browser }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
];
```

**Comment by yonta** [comment]
## ESLint の設定移行ガイド
 
- https://eslint.org/docs/latest/use/configure/migration-guide

以下コマンドで変換できるとある。

```
$ yarn dlx  @eslint/migrate-config .eslintrc.json
```

SAKAZUKIの設定を自動変換してみて、生成されたeslint.config.mjs

```mjs
import jsdoc from "eslint-plugin-jsdoc";
import globals from "globals";
import typescriptEslint from "@typescript-eslint/eslint-plugin";
import tsdoc from "eslint-plugin-tsdoc";
import tsParser from "@typescript-eslint/parser";
import path from "node:path";
import { fileURLToPath } from "node:url";
import js from "@eslint/js";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: js.configs.recommended,
    allConfig: js.configs.all
});

export default [{
    ignores: ["coverage/", "app/assets/builds"],
}, ...compat.extends("eslint:recommended", "prettier", "plugin:jsdoc/recommended-typescript"), {
    plugins: {
        jsdoc,
    },

    linterOptions: {
        reportUnusedDisableDirectives: true,
    },

    languageOptions: {
        globals: {
            ...globals.browser,
        },

        ecmaVersion: 5,
        sourceType: "module",
    },

    rules: {
        indent: ["error", 2],
        "linebreak-style": ["error", "unix"],

        quotes: ["error", "double", {
            avoidEscape: true,
        }],

        semi: ["error", "never"],

        "no-unused-vars": ["error", {
            varsIgnorePattern: "^_",
            argsIgnorePattern: "^_",
        }],

        "jsdoc/require-asterisk-prefix": ["warn"],
        "jsdoc/require-description": ["warn"],
        "jsdoc/require-throws": ["warn"],
        "jsdoc/sort-tags": ["warn"],

        "jsdoc/tag-lines": ["warn", "any", {
            startLines: 1,
        }],
    },
}, ...compat.extends(
    "eslint:recommended",
    "plugin:@typescript-eslint/strict-type-checked",
    "plugin:@typescript-eslint/stylistic-type-checked",
    "prettier",
).map(config => ({
    ...config,
    files: ["**/*.ts", "**/*.tsx"],
})), {
    files: ["**/*.ts", "**/*.tsx"],

    plugins: {
        "@typescript-eslint": typescriptEslint,
        tsdoc,
    },

    languageOptions: {
        parser: tsParser,
        ecmaVersion: 5,
        sourceType: "script",

        parserOptions: {
            tsconfigRootDir: ".",
            project: true,
        },
    },

    rules: {
        "@typescript-eslint/no-unused-vars": ["error", {
            varsIgnorePattern: "^_",
            argsIgnorePattern: "^_",
        }],

        "@typescript-eslint/consistent-type-imports": "error",
        "@typescript-eslint/consistent-type-definitions": ["warn", "type"],
        "tsdoc/syntax": "warn",
    },
}];
```

なんかだいぶ複雑じゃない？

## 生成された設定でESLint実行

試しにこれでESLintかけてみると、見事にエラー。

```console
$ yarn eslint

Oops! Something went wrong! :(

ESLint: 9.22.0

ConfigError: Config (unnamed): Key "plugins": Cannot redefine plugin "jsdoc".
    at rethrowConfigError (/home/kei/git/sakazuki/node_modules/@eslint/config-array/dist/cjs/index.cjs:328:8)
    at /home/kei/git/sakazuki/node_modules/@eslint/config-array/dist/cjs/index.cjs:1174:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfigWithStatus (/home/kei/git/sakazuki/node_modules/@eslint/config-array/dist/cjs/index.cjs:1167:43)
    at FlatConfigArray.getConfig (/home/kei/git/sakazuki/node_modules/@eslint/config-array/dist/cjs/index.cjs:1196:15)
    at entryFilter (/home/kei/git/sakazuki/node_modules/eslint/lib/eslint/eslint-helpers.js:282:40)
    at async NodeHfs.<anonymous> (file:///home/kei/git/sakazuki/node_modules/@humanfs/core/src/hfs.js:574:24)
    at async NodeHfs.walk (file:///home/kei/git/sakazuki/node_modules/@humanfs/core/src/hfs.js:614:3)
    at async globSearch (/home/kei/git/sakazuki/node_modules/eslint/lib/eslint/eslint-helpers.js:323:26)
```

**Comment by yonta** [comment]
最小値から今の設定を追加した方が良い気がする。

## 既存コンフィグ

- js関係
  - ブラウザ環境（`document.getElementById`とか使う）
  - es2022（これはもっと最新でもOK）
  - module（これは今もいるか不明）
  - 無視ファイル
    - レポジトリのcoverageとapp/assets/buildsが指定してある
    - そもそもgitignoreにもこれらは書いてある
    - そもそも`yarn lint:eslint`ではgitignoreを使って無視しているので、今も必要ないのでは
  - jsdocプラグインとjsdoc/recommend-typescriptをオン
    - 細かなルール設定あり
  - eslint:recommend、prettierをオン
  - ルール設定
    - インデント２
    - 改行はLinux系のLF
    - ダブルクオートを使う、ただしダブルクオートが出てくるときはシングルクオートOK
    - セミコロンはつけない
    - 未使用変数はアンダーバースタートで回避できる
  - 消し忘れたdisableマジックコメントはエラー
- ts関係
  - tsdocプラグインを使う
    - syntaxエラーをオン
  - strict-type-checkedとstylistic-type-checkedをオン、厳しめ
  - ルール設定
    - 未使用変数はアンダーバースタートで回避できる
    - typeのインポートは`import`ではなく`import type`を強制
    - interfaceの使用を禁止し、typeを強制

**Comment by yonta** [comment]
ややこしので整理

- https://eslint.style/guide/config-presets
- https://eslint.style/guide/getting-started

@stylistic/eslint-pluginが統合プラグイン

- JSとかTSとかJSX統合プラグイン
  - *-jsや-tsや-jsxや-plusの4つを統合して提供
- ファクトリー関数`customize`を提供
- recommendedルールを提供

@stylistic/eslint-plugin-jsはjs用最低限

- 我々が必要なものはほぼこれでOK
- -tsも使う？

**Comment by yonta** [comment]
フラットコンフィグは順番関係ない？
以下の二つの順番を上下変えてみても、結果に影響なくrecommendedのほうが優先される。
具体的にはどちらの順番で書いてもシングルクオート使えとかのエラーが大量に出ちゃう。

```js
  // プラグイン設定
  {
    plugins: {
      "@stylistic/js": stylisticJs,
    },
    rules: {
      // Styleプラグイン設定
      "@stylistic/js/indent": ["error", 2],
      "@stylistic/js/linebreak-style": ["error", "unix"],
      "@stylistic/js/quotes": ["error", "double", { avoidEscape: true }],
      "@stylistic/js/semi": ["error", "never"],
    },
  },
```
```js
  stylistic.configs.recommended,
```

**Comment by yonta** [comment]
できた。
以下のように書けばrecommended使いつつカスタマイズできる。
@stylistic/***に名前が展開されているのか。
フラットコンフィグは下に書くほど優先度が高くなる。


```js
  stylistic.configs.recommended,
  {
    rules: {
      "@stylistic/quotes": ["error", "double", { avoidEscape: true }],
    },
  },
```

最後`...hoge`はスプレッド構文なので、ただの配列展開？
tseslintだけこれが使われてるのが理解できてない。

**Comment by yonta** [comment]
報告の形式も変わるのか。

```
    plugins: {
      "@stylistic/js": stylisticJs,
    },
```
の形式ならエラーも`@stylistic/js/quotes`のようになる。

```
  {
    rules: {
      "@stylistic/quotes": ["error", "double", { avoidEscape: true }],
    },
  },
```
の形式ならエラーも`@stylistic/quotes`のようになる

**Comment by yonta** [comment]
plugins方式のほうが明確に名前空間を区切れてどの設定なのか明示的でわかりやすいように見える

**Comment by yonta** [comment]
必要ないインラインディレクティブのエラーについて調べてたら、ここに載ってる
 
- https://eslint.org/docs/latest/use/configure/configuration-files#globally-ignoring-files-with-ignores

```
    linterOptions: {
      reportUnusedDisableDirectives: "error",
      reportUnusedInlineConfigs: "error",
    },
```

みたいなのをfilesの下に書けばいいのかな

**Comment by yonta** [comment]
ecmaVersionsはデフォルトでlatestだから設定しなくていいな

**Comment by yonta** [comment]
以下みたいに書くと、書いた4ルールしか適用されてないな。
recommendsやallをextendして書かないとだめだ。

```
  // @stylistic-plugin-jsの設定
  {
    plugins: {
      "@stylistic/js": stylisticJs,
    },
    rules: {
      "@stylistic/js/indent": ["error", 2],
      "@stylistic/js/linebreak-style": ["error", "unix"],
      "@stylistic/js/quotes": ["error", "double", { avoidEscape: true }],
      "@stylistic/js/semi": ["error", "never"],
    },
  },
```

**Comment by yonta** [comment]
stylistic/eslint-plugin-jsはallしかなくreccomendedがない…。
allを使うととんでもないエラーが大量に出る。
理由はprettierとの整合性がとれてないから。

先にeslint-config-prettier入れたほうがいいな！

**Comment by yonta** [comment]
そもそもeslint-config-prettier入れると、@stylistic/js/indentとかは無効化されるのか。

- https://github.com/prettier/eslint-config-prettier/blob/main/index.js

それはそう。
インデントとかは全ファイルprettier書ける前提になるから、ESLintでチェックしなくてよい。
prettierをかけて、pretter checkで検知すればよい。
うちのSAKAZUKIもそうなっている。

**Comment by yonta** [comment]
あーーーー！！
app/javascriptのみを対象にすると、eslint.config.mjs自身やjsonが対象にならないのか。

**Comment by yonta** [comment]
後で考えよう

**Comment by yonta** [comment]
typescript-eslintをいれるぞい

**Comment by yonta** [comment]
TypeCheckedつきだと、Node20以上が必要。ちょうど22に上げといてよかった。

**Comment by yonta** [comment]
個人的には、

- JSにESLintの設定をする
- TSにtypescript-eslintの設定をする

のつもりだった。
けど、typescript-eslintのドキュメントを見ると違うようだ。
 
- https://typescript-eslint.io/packages/typescript-eslint/#usage-with-other-plugins

このドキュメントによると、

- 全ファイルにeslint-tslintをかけるつもりで書く
- 最後にJSには`disableTypeChecked`を追加して、typescript-eslintのリント内容から一部除外を設定する

のやり方が書かれている。
こっちのほうが推奨なのかな。

**Comment by yonta** [comment]
TSDocはフラットコンフィグをサポートしていないな。
しかもJSDocのほうがTypeSciprt対応した`flat/***-typescript`ルールを持っている。
JSDocだけ使うようにしていこう。

**Comment by yonta** [comment]
`recommend`でなく、各種グループを全部追加して、全部オンにするぞ！

**Comment by yonta** [comment]
今のESLintはgitignoreファイル読み込む設定あるじゃん！
神～～～ 
 
- https://eslint.org/docs/latest/use/configure/ignore#including-gitignore-files

**Comment by yonta** [comment]
gitignoreファイルは読み込めたけど、やっぱ探索範囲が広がるせいかめちゃくちゃ遅くなるな。
具体的には3秒が12秒くらいに伸びてる。
それでいて増えた対象ファイルは.prettierrc.jsくらいしかない。

```console
$ hyperfine -i 'yarn lint:eslint' 'yarn eslint ./app/javascript'
Benchmark 1: yarn lint:eslint
  Time (mean ± σ):     11.485 s ±  0.240 s    [User: 16.310 s, System: 1.547 s]
  Range (min … max):   11.216 s … 11.904 s    10 runs

  Warning: Ignoring non-zero exit code.

Benchmark 2: yarn eslint ./app/javascript
  Time (mean ± σ):      2.847 s ±  0.023 s    [User: 4.267 s, System: 0.400 s]
  Range (min … max):    2.805 s …  2.871 s    10 runs

  Warning: Ignoring non-zero exit code.

Summary
  yarn eslint ./app/javascript ran
    4.03 ± 0.09 times faster than yarn lint:eslint
```

**Comment by yonta** [comment]
`$ yarn eslint ./app/javascript/ ./.prettierrc.js`でいいな！！！

**Comment by yonta** [comment]
npmを「eslint config」で検索するとおもしろい。
各社やプラットフォーム対応のconfigが色々でてくる。

同じように「eslint plugin」で検索すると、json対応など各種プラグインが出てくる。

**Comment by yonta** [comment]
prettierの設定、JSで書いてるけどこれはJSONでもいい気がしてきた。
難しいことしてないんだし

**Comment by yonta** [comment]
Prettierの公式見てると、JSONだけでなくpackage.json内にも書けるのか。
Prettierの方針としても、「なるべく設定せずにデフォルトでそろえる」だし、
SAKAZUKIも設定しているのはセミコロン無しくらいしかない。
package.jsonのdevDependencyにprettierがあるわけだし、package.json内にまとめちゃうのありだな。

- https://prettier.io/docs/configuration
